config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "flats#index"

  resources :flats, only: %i[index show new edit] do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show]
  before_action :set_flat, only: [:new, :create]

  def new
    @booking = Booking.new
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :nb_people)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<%= simple_form_for [@flat, @booking] do |f| %>
<%# date_picker %>

  <%= f.input :check_in, as: :string,
            input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :check_out, as: :string,
            input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :nb_people, as: :integer %>
  <%= f.button :submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p><strong>Booking ID:</strong> <%= @booking.id %></p>
<p><strong>Check-in Date:</strong> <%= @booking.check_in %></p>
<p><strong>Check-out Date:</strong> <%= @booking.check_out %></p>
<p><strong>Total Price:</strong> <%= @booking.flat.price_per_night %></p>
<%= link_to 'Back to flat', flat_path(@booking.flat) %>

app/views/flats/_form.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <h1><%= title %></h1>
      <%= simple_form_for flat do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/edit.html.erb
<%= render partial: "form", locals: { flat: @flat, title: "Edit Flat", button_text: "Update Restaurant"}%>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col">
      <div class="mb-3">
        <h1>All our Flats (<%=@flats.size%> )</h1>
      </div>
    </div>
  </div>
  <%# <div class="row row-cols-4 row-cols-md-3 g-4"> %>
  <%# <div class="row"> %>
    <div class="row row-cols-md-2 row-cols-lg-3 g-4 card-group">
      <% @flats.each do |flat|%>
      <div class="col">
        <div class="card shadow p-3 mb-5 bg-body-tertiary rounded h-100">
          <div class="card-body">
            <div class="row">
              <div class="col-lg-12">
                <h5 class="card-title"><%= flat.name%></h5>
                <p class="card-text"><%= flat.address%></p>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">
                <i class="fa fa-group"></i>
                <small><%= flat.number_of_guests%></small>
              </div>
              <div class="col-lg-6 text-end" >
                <i class='fas fa-euro-sign'></i>
                <small><%= flat.price_per_night%></small>
              </div>
            </div>
          </div>
          <div class="card-footer bg-transparent">
            <div class="row">
              <div class="col-lg-6">
                <small class="text-body-secondary">
                  <%= link_to "More info", flat_path(flat)%>
                </small>
              </div>
              <div class="col-lg-6 text-end">
                <small class="text-body-secondary">
                  <%= link_to flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                    <i class="fa-solid fa-trash"></i>
                  <%end%>
                </small>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%end%>
    </div>
  <%# </div> %>
</div>

app/views/flats/new.html.erb
<%= render partial: "form", locals: { flat: @flat, title: "New Flat", button_text: "Create Restaurant"}%>

app/views/flats/show.html.erb
<div class="container-mt-3">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <h1><%= @flat.name%></h1>
      <h3><%= @flat.address %></h3>
      <p><%= @flat.description %></p>
      <div class="row">
        <div class="col-lg-6">
          <p><i class='fas fa-euro-sign'></i><%= @flat.price_per_night %></p>
        </div>
        <div class="col-lg-6">
          <p><i class="fa fa-group"></i><%= @flat.number_of_guests %></p>
        </div>
      </div>
      <div class="row">
        <small class="text-body-secondary">
          <%= link_to "Edit", edit_flat_path(@flat)%>
        </small>
        <small class="text-body-secondary">
          <%= link_to "Book", new_flat_booking_path(@flat)%>
        </small>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Simple Airbnb</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", flats_path, class: "nav-link active"%>
        </li>
      </ul>
      <form class="d-flex">
        <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-success" %>
        <%# <button class="btn btn-outline-success" type="submit">Add Flat</button> %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_test.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Simple Airbnb</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-success" %>
        <%# <button class="btn btn-outline-success" type="submit">Add Flat</button> %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>